config/routes.rb
Rails.application.routes.draw do
  resources :produtos
  root 'produtos#index'

  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/produto.rb
class Produto < ApplicationRecord
    validates :nome_produto, presence:true
    validates :quantidade, presence:true
    validates :valor_compra, presence:true
    validates :categoria, presence:true
    validates :fornecedor, presence:true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/produtos_controller.rb
class ProdutosController < ApplicationController
  def index
    @produto = Produto.all
  end

  def new
    @produto = Produto.new
  end

  def create
        @produto = Produto.new(produto_params)
      if @produto.save
        redirect_to produto_path, notice: 'Produto Cadastrado com Sucesso'
    else
      render :new
    end
   end

   private

   def produto_params
       params.require(:produto).permit(:nome_produto, :valor_compra, :quantidade, :categoria, :fornecedor)
   end

  def edit
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/produtos_helper.rb
module ProdutosHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Vendas2</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0-beta1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-0evHe/X+R7YkIZDRvuzKMRqM+OrBnVFBL6DOitfPri4tjfHxaWutUpFmBp4vmVor" crossorigin="anonymous">
  </head>

  <body>
    <div class="container">
 <% if notice.present? %>
 <div class="alert alert-info" role="alert"><%= notice %></div>
 <% end %>
 <% if alert.present? %>
 <div class="alert alert-danger" role="alert"><%= alert %></div>
 <% end %>

 <%= yield %>
</div>
  </body>
      <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0-beta1/dist/js/bootstrap.bundle.min.js" integrity="sha384-pprn3073KE6tl6bjs2QrFaJGz5/SUsLqktiwsUTF55Jfv3qYSDhgCecCxMW52nD2" crossorigin="anonymous"></script>
</html>

app/views/produtos/edit.html.erb
<h1>Produtos#edit</h1>
<p>Find me in app/views/produtos/edit.html.erb</p>

app/views/produtos/index.html.erb
<h1>Produtos</h1>
<%= link_to 'Cadastrar', new_produto_path, class: 'btn btn-primary' %>
<% if @produto.empty? %>
 <p>Nenhum Produto encontrado</p>
<% else %>
 <table class = "table table-bordered table-hover">
 <thead>

 <th>Nome</th>
 <th>Quntidade</th>
 <th>Preço</th>
 <th>Categoria</th>
 <th>Fornecedor</th>
 </thead>
 <tbody>
 <% @produto.each do |produto| %>
 <tr>
 <td><%= produto.nome_produto %></td>
 <td><%= produto.quantidade %></td>
 <td><%= produto.valor_compra %></td>
 <td><%= produto.categoria %></td>
 <td><%= produto.fornecedor %></td>
 </tr>
 <% end %>
 </tbody>
 </table>
<% end %>

app/views/produtos/new.html.erb
<h1>Cadastrar Produtos</h1>
<%= link_to 'Voltar', produtos_path, class: 'btn btn-primary' %>
<%= simple_form_for @produto do |f| %>
 <%= f.input :nome_produto, required: true, label: 'Nome do Produto' %>
 <%= f.input :valor_compra,  label: "Valor do Produto" %>
 <%= f.input :quantidade, required: true, label: "Quantidade" %>
 <%= f.input :categoria, required: true, label: "Categoria" %>
 <%= f.input :categoria, required: true, label: "Fornecedor" %>
 <br>
 <%= f.button :submit, 'Enviar', class: 'btn-primary' %>
<% end %>